#!/bin/bash

getent group pepe > /dev/null 2>&1 || groupadd pepe
if getent group pepe > /dev/null 2>&1; then id pepe > /dev/null 2>&1 || useradd -g pepe -d /opt/pepe/api pepe;fi
id pepe > /dev/null 2>&1 && /usr/bin/systemctl enable pepe-api || true
mkdir -p /opt/logs/pepe/api || true
test -d /opt/logs/pepe/api && chown -R pepe.pepe /opt/logs/pepe/api

#EOF